theme: jekyll-theme-minimal
title: Portfolio
description: Joe Wainer, Technical Writer
logo: https://github.com/JoeWainer/joewainer.github.io/blob/main/resources/joeprofile.jpg?raw=true
download: false
